services:
  linkding:
    image: sissbruecker/linkding:1.44.1
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PANEL_APP_PORT_HTTP}:9090"
    volumes:
      - ./data:/etc/linkding/data
    environment:
      - LD_SUPERUSER_NAME=${LD_SUPERUSER_NAME:-admin}
      - LD_SUPERUSER_PASSWORD=${LD_SUPERUSER_PASSWORD:-adminadmin}
    restart: unless-stopped
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true