services:
  linkding:
    image: sissbruecker/linkding:1.43.0
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PANEL_APP_PORT_HTTP}:9090"
    volumes:
      - ./data:/etc/linkding/data
    restart: unless-stopped
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true