services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.3.2 
    container_name: mealie
    restart: always
    ports:
        - ${PANEL_APP_PORT_HTTP}:9000
    deploy:
      resources:
        limits:
          memory: 1000M 
    volumes:
      - mealie-data:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Asia/Shanghai
      BASE_URL:${PANEL_APP_BASE_URL} 

    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"
volumes:
  mealie-data:

networks:
  1panel-network:
    external: true